### ISSUE TITLE
error in desktop.el restore (desktop-read) when used non-trivially after a while

### ISSUE THREAD

**Issue by raymond-w-ko** [florommel/bufferlo#1]
When I have several projects (including tramp ones), and tabs open, I save my tabs, windows, and buffers. Then when I restart Emacs and restore with `(desktop-read)` I get the following error and backtrace:

```emacs
Debugger entered--Lisp error: (wrong-type-argument window-valid-p #<window 3>)
  bufferlo--window-state-put(... #<window 3> safe)
  apply(bufferlo--window-state-put (... #<window 3> safe))
  window-state-put(... #<window 3> safe)
  #<subr frameset--restore-frame>(...)
  bufferlo--activate(...)
  apply(bufferlo--activate ...)
  frameset--restore-frame(...)
  frameset-restore(...)
  desktop-restore-frameset()
  desktop-read(nil nil)
  funcall-interactively(desktop-read nil nil)
  command-execute(desktop-read record)
  execute-extended-command(nil "desktop-read" nil)
  funcall-interactively(execute-extended-command nil "desktop-read" nil)
  command-execute(execute-extended-command)
```
I've trimmed a lot of the first arguments as they are very large and contains private stuff.

I'm not sure how to reproduce just opening a few tabs do not work. Maybe it's a combo of window splits and `*` buffers that don't survive a save/restore...

**Comment by florommel** [comment]
Thank you. Commit 82f51c3 should resolve the issue.
Can you please check?

The problem was that windows for non-existent buffers get deleted during `window-state-put` before `bufferlo--window-state-put` is called.

**Comment by florommel** [comment]
I assume that this is fixed. Please feel free to comment if the problem persists and I will reopen the issue.
