### ISSUE TITLE
Missing from ELPA

### ISSUE THREAD

**Issue by shobute** [florommel/bufferlo#2]
I love this package, it makes Emacs a real joy to use and I recommend it to everyone I meet. The only problem is it's not as simple as running `package-install` as it's missing from ELPA. Are there any plans to add this to the package archive?

**Comment by florommel** [comment]
Thanks! So far, there have been no plans in this regard. But if there is interest, we can do that.
I checked the MELPA contribution guidelines. Bufferlo should already meet most of the requirements, but I haven't looked at everything in detail yet.

**Comment by florommel** [comment]
Bufferlo is now in GNU ELPA!
https://elpa.gnu.org/packages/bufferlo.html
